v <- integer() #initialize empty vector

v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG FP2-REF'$signal, method = 'pearson'), after = length(0))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG F3-REF'$signal, method = 'pearson'), after = length(1))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG F4-REF'$signal, method = 'pearson'), after = length(2))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG C3-REF'$signal, method = 'pearson'), after = length(3))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG C4-REF'$signal, method = 'pearson'), after = length(4))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG P3-REF'$signal, method = 'pearson'), after = length(5))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(6))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(7))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(8))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(9))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(10))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(11))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(12))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(13))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(14))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(15))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(16))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(17))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(18))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(19))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(20))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(21))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(22))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(23))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(24))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(25))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(26))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(27))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(28))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(29))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(30))
v <- append(v, cor(sig$'EEG FP1-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(31))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG F3-REF'$signal, method = 'pearson'), after = length(32))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG F4-REF'$signal, method = 'pearson'), after = length(33))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG C3-REF'$signal, method = 'pearson'), after = length(34))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG C4-REF'$signal, method = 'pearson'), after = length(35))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG P3-REF'$signal, method = 'pearson'), after = length(36))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(37))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(38))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(39))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(40))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(41))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(42))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(43))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(44))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(45))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(46))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(47))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(48))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(49))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(50))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(51))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(52))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(53))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(54))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(55))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(56))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(57))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(58))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(59))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(60))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(61))
v <- append(v, cor(sig$'EEG FP2-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(62))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG F4-REF'$signal, method = 'pearson'), after = length(63))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG C3-REF'$signal, method = 'pearson'), after = length(64))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG C4-REF'$signal, method = 'pearson'), after = length(65))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(67))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(68))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(69))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(70))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(71))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(72))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(73))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(74))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(75))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(76))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(77))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(78))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(79))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(80))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(81))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(82))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(83))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(84))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(85))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(86))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(87))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(88))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(89))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(90))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(91))
v <- append(v, cor(sig$'EEG F3-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(92))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG C3-REF'$signal, method = 'pearson'), after = length(93))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG C4-REF'$signal, method = 'pearson'), after = length(94))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG P3-REF'$signal, method = 'pearson'), after = length(95))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(96))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(97))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(98))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(99))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(100))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(101))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(102))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(103))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(104))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(105))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(106))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(107))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(108))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(109))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(110))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(111))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(112))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(113))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(114))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(115))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(116))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(117))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(118))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(119))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(120))
v <- append(v, cor(sig$'EEG F4-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(121))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG C4-REF'$signal, method = 'pearson'), after = length(122))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG P3-REF'$signal, method = 'pearson'), after = length(123))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(124))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(125))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(126))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(127))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(128))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(129))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(130))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(131))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(132))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(133))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(134))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(135))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(136))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(137))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(138))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(139))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(140))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(141))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(142))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(143))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(144))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(145))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(146))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(147))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(148))
v <- append(v, cor(sig$'EEG C3-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(149))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG P3-REF'$signal, method = 'pearson'), after = length(150))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(151))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(152))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(153))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(154))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(155))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(156))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(157))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(158))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(159))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(160))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(161))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(162))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(163))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(164))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(165))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(166))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(167))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(168))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(169))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(170))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(171))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(172))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(173))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(174))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(175))
v <- append(v, cor(sig$'EEG C4-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(176))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG P4-REF'$signal, method = 'pearson'), after = length(177))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(178))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(179))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(180))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(181))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(182))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(183))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(184))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(185))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(186))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(187))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(188))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(189))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(190))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(191))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(192))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(193))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(194))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(195))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(196))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(197))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(198))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(199))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(200))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(201))
v <- append(v, cor(sig$'EEG P3-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(202))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG O1-REF'$signal, method = 'pearson'), after = length(203))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(204))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(205))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(206))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(207))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(208))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(209))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(210))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(211))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(212))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(213))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(214))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(215))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(216))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(217))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(218))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(219))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(220))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(221))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(222))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(223))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(224))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(225))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(226))
v <- append(v, cor(sig$'EEG P4-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(227))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG O2-REF'$signal, method = 'pearson'), after = length(228))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(229))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(230))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(231))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(232))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(233))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(234))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(235))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(236))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(237))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(238))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(239))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(240))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(241))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(242))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(243))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(244))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(245))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(246))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(247))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(248))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(249))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(250))
v <- append(v, cor(sig$'EEG O1-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(251))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG F7-REF'$signal, method = 'pearson'), after = length(252))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(253))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(254))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(255))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(256))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(257))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(258))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(259))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(260))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(261))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(262))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(263))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(264))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(265))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(266))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(267))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(268))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(269))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(270))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(271))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(272))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(273))
v <- append(v, cor(sig$'EEG O2-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(274))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG F8-REF'$signal, method = 'pearson'), after = length(275))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(276))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(277))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(278))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(279))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(280))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(281))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(282))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(283))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(284))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(285))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(286))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(287))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(288))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(289))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(290))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(291))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(292))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(293))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(294))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(295))
v <- append(v, cor(sig$'EEG F7-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(296))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG T3-REF'$signal, method = 'pearson'), after = length(297))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(298))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(299))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(300))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(301))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(302))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(303))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(304))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(305))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(306))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(307))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(308))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(309))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(310))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(311))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(312))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(313))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(314))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(315))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(316))
v <- append(v, cor(sig$'EEG F8-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(317))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG T4-REF'$signal, method = 'pearson'), after = length(318))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(319))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(320))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(321))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(322))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(323))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(324))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(325))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(326))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(327))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(328))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(329))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(330))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(331))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(332))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(333))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(334))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(335))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(336))
v <- append(v, cor(sig$'EEG T3-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(337))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG T5-REF'$signal, method = 'pearson'), after = length(338))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(339))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(340))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(341))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(342))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(343))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(344))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(345))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(346))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(347))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(348))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(349))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(350))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(351))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(352))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(353))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(354))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(355))
v <- append(v, cor(sig$'EEG T4-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(356))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG T6-REF'$signal, method = 'pearson'), after = length(357))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(358))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(359))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(360))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(361))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(362))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(363))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(364))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(365))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(366))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(367))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(368))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(369))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(370))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(371))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(372))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(373))
v <- append(v, cor(sig$'EEG T5-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(374))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG A1-REF'$signal, method = 'pearson'), after = length(375))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(376))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(377))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(378))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(379))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(380))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(381))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(382))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(383))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(384))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(385))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(386))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(387))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(388))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(389))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(390))
v <- append(v, cor(sig$'EEG T6-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(391))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG A2-REF'$signal, method = 'pearson'), after = length(392))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(393))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(394))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(395))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(396))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(397))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(398))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(399))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(400))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(401))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(402))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(403))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(404))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(405))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(406))
v <- append(v, cor(sig$'EEG A1-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(407))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG FZ-REF'$signal, method = 'pearson'), after = length(408))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(409))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(410))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(411))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(412))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(413))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(414))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(415))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(416))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(417))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(418))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(419))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(420))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(421))
v <- append(v, cor(sig$'EEG A2-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(422))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG CZ-REF'$signal, method = 'pearson'), after = length(423))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(424))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(425))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(426))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(427))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(428))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(429))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(430))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(431))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(432))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(433))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(434))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(435))
v <- append(v, cor(sig$'EEG FZ-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(436))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG PZ-REF'$signal, method = 'pearson'), after = length(437))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(438))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(439))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(440))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(441))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(442))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(443))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(444))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(445))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(446))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(447))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(448))
v <- append(v, cor(sig$'EEG CZ-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(449))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG ROC-REF'$signal, method = 'pearson'), after = length(450))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(451))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(452))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(453))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(454))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(455))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(456))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(457))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(458))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(459))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(460))
v <- append(v, cor(sig$'EEG PZ-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(461))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG LOC-REF'$signal, method = 'pearson'), after = length(462))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(463))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(464))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(465))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(466))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(467))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(468))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(469))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(470))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(471))
v <- append(v, cor(sig$'EEG ROC-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(472))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG EKG1-REF'$signal, method = 'pearson'), after = length(473))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(474))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(475))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(476))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(477))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(478))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(479))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(480))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(481))
v <- append(v, cor(sig$'EEG LOC-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(482))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EMG-REF'$signal, method = 'pearson'), after = length(483))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(484))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(485))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(486))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(487))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(488))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(489))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(490))
v <- append(v, cor(sig$'EEG EKG1-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(491))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG 26-REF'$signal, method = 'pearson'), after = length(492))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(493))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(494))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(495))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(496))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(497))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(498))
v <- append(v, cor(sig$'EMG-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(499))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'EEG 27-REF'$signal, method = 'pearson'), after = length(500))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(501))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(502))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(503))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(504))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(505))
v <- append(v, cor(sig$'EEG 26-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(506))
v <- append(v, cor(sig$'EEG 27-REF'$signal, sig$'EEG 28-REF'$signal, method = 'pearson'), after = length(507))
v <- append(v, cor(sig$'EEG 27-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(508))
v <- append(v, cor(sig$'EEG 27-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(509))
v <- append(v, cor(sig$'EEG 27-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(510))
v <- append(v, cor(sig$'EEG 27-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(511))
v <- append(v, cor(sig$'EEG 27-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(512))
v <- append(v, cor(sig$'EEG 28-REF'$signal, sig$'EEG 29-REF'$signal, method = 'pearson'), after = length(513))
v <- append(v, cor(sig$'EEG 28-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(514))
v <- append(v, cor(sig$'EEG 28-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(515))
v <- append(v, cor(sig$'EEG 28-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(516))
v <- append(v, cor(sig$'EEG 28-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(517))
v <- append(v, cor(sig$'EEG 29-REF'$signal, sig$'EEG 30-REF'$signal, method = 'pearson'), after = length(518))
v <- append(v, cor(sig$'EEG 29-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(519))
v <- append(v, cor(sig$'EEG 29-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(520))
v <- append(v, cor(sig$'EEG 29-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(521))
v <- append(v, cor(sig$'EEG 30-REF'$signal, sig$'EEG T1-REF'$signal, method = 'pearson'), after = length(522))
v <- append(v, cor(sig$'EEG 30-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(523))
v <- append(v, cor(sig$'EEG 30-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(524))
v <- append(v, cor(sig$'EEG T1-REF'$signal, sig$'EEG T2-REF'$signal, method = 'pearson'), after = length(525))
v <- append(v, cor(sig$'EEG T1-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(526))
v <- append(v, cor(sig$'EEG T2-REF'$signal, sig$'PHOTIC-REF'$signal, method = 'pearson'), after = length(527))

#find index position and value for min of vector
which.min(v)
min(v)

#find index position and value for max of vector
which.max(v)
max(v)

z <- c(min(v), max(v)) #vector of values for min and max correlations 
y <- c(which.min(v), which.max(v)) #vector of index positions for min and max correlations 
plot(v, ylab ="correlations (v)" ,col=ifelse(v==z[1] | v==z[2], "red", "black"), main = "Correlations Plot w/ Min & Max")


